#ifndef BEATLED_CONSTANTS_H
#define BEATLED_CONSTANTS_H

#define SAMPLE_RATE 16000
#define FFT_SIZE 1024
#define INPUT_BUFFER_SIZE 256
#define INPUT_SHIFT 2

#define FFT_BINS_SKIP 5
#define FFT_MAG_MAX 2000.0

#define MAGNITUDE_HISTORY_SIZE 10 * SAMPLE_RATE / INPUT_BUFFER_SIZE
// 10 sec * 16000 samples per sec / 64 samples for every step forward

#define BPM_MIN 80
#define BPM_MAX 200

#define LED_CORE_SLEEP_MS 10
#define CONTROL_CORE_SLEEP_MS 20

#define MAX_INTERCORE_QUEUE_COUNT 64

// LED messages
#define ERROR_BLINK_SPEED 100
#define MESSAGE_BLINK_SPEED 400

#define ERROR_WIFI 4
#define ERROR_COMMAND 6

#define MESSAGE_WELCOME 2
#define MESSAGE_CONNECTED 3
#define MESSAGE_TIME_UPDATED 4
#define MESSAGE_HELLO 5

#define UDP_SERVER_PORT 9090
#define UDP_PORT 8765

#endif // BEATLED_CONSTANTS_H