# BEATLED_PROTOCOL_BUILD_DEFINE: BEATLED_PROTOCOL_VERSION_MAJOR, SDK major version number, type=int, group=pico_base
# BEATLED_PROTOCOL_CONFIG: BEATLED_PROTOCOL_VERSION_MAJOR, SDK major version number, type=int, group=pico_base
set(BEATLED_PROTOCOL_VERSION_MAJOR 1)
# BEATLED_PROTOCOL_BUILD_DEFINE: BEATLED_PROTOCOL_VERSION_MINOR, SDK minor version number, type=int, group=pico_base
# BEATLED_PROTOCOL_CONFIG: BEATLED_PROTOCOL_VERSION_MINOR, SDK minor version number, type=int, group=pico_base
set(BEATLED_PROTOCOL_VERSION_MINOR 4)
# BEATLED_PROTOCOL_BUILD_DEFINE: BEATLED_PROTOCOL_VERSION_REVISION, SDK version revision, type=int, group=pico_base
# BEATLED_PROTOCOL_CONFIG: BEATLED_PROTOCOL_VERSION_REVISION, SDK version revision, type=int, group=pico_base
set(BEATLED_PROTOCOL_VERSION_REVISION 0)
# BEATLED_PROTOCOL_BUILD_DEFINE: BEATLED_PROTOCOL_VERSION_PRE_RELEASE_ID, optional SDK pre-release version identifier, type=string, group=pico_base
# BEATLED_PROTOCOL_CONFIG: BEATLED_PROTOCOL_VERSION_PRE_RELEASE_ID, optional SDK pre-release version identifier, type=string, group=pico_base
#set(BEATLED_PROTOCOL_VERSION_PRE_RELEASE_ID develop)

# BEATLED_PROTOCOL_BUILD_DEFINE: BEATLED_PROTOCOL_VERSION_STRING, SDK version, type=string, group=pico_base
# BEATLED_PROTOCOL_CONFIG: BEATLED_PROTOCOL_VERSION_STRING, SDK version, type=string, group=pico_base
set(BEATLED_PROTOCOL_VERSION_STRING "${BEATLED_PROTOCOL_VERSION_MAJOR}.${BEATLED_PROTOCOL_VERSION_MINOR}.${BEATLED_PROTOCOL_VERSION_REVISION}")

if (BEATLED_PROTOCOL_VERSION_PRE_RELEASE_ID)
    set(BEATLED_PROTOCOL_VERSION_STRING "${BEATLED_PROTOCOL_VERSION_STRING}-${BEATLED_PROTOCOL_VERSION_PRE_RELEASE_ID}")
endif()
