#ifndef BLINK_CONSTANTS_H
#define BLINK_CONSTANTS_H


// LED messages
#define ERROR_BLINK_SPEED 100
#define MESSAGE_BLINK_SPEED 400

#define ERROR_WIFI 4
#define ERROR_COMMAND 6

#define MESSAGE_WELCOME 2
#define MESSAGE_CONNECTED 3
#define MESSAGE_TIME_UPDATED 4
#define MESSAGE_HELLO 5



#endif // BLINK_CONSTANTS_H
